name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out GitHub repository
        uses: actions/checkout@v6

      - name: Sync to Hugging Face Hub
        uses: huggingface/hub-sync@v0.1.0
        with:
          github_repo_id: ${{ github.repository }}
          huggingface_repo_id: thebestian/wm-tippspiel-2026
          repo_type: space
          space_sdk: docker
          hf_token: ${{ secrets.HF_TOKEN }}
